// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrEN1TWWcqBEBBtiPj62wVrTAvDOx9Qn8',
    appId: '1:149274182505:web:1062ad129fb8ef1914f3f8',
    messagingSenderId: '149274182505',
    projectId: 'loyalapp-2beb0',
    authDomain: 'loyalapp-2beb0.firebaseapp.com',
    storageBucket: 'loyalapp-2beb0.appspot.com',
    measurementId: 'G-5QL9L896NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXbikuy5_xVmQHAX_J7gx69i8Nh24qN8',
    appId: '1:149274182505:android:70858b12059bea3114f3f8',
    messagingSenderId: '149274182505',
    projectId: 'loyalapp-2beb0',
    storageBucket: 'loyalapp-2beb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgXiKztzfEQarlh9XpjsjgueND1pcUqew',
    appId: '1:149274182505:ios:1296adf4eeecb66a14f3f8',
    messagingSenderId: '149274182505',
    projectId: 'loyalapp-2beb0',
    storageBucket: 'loyalapp-2beb0.appspot.com',
    iosClientId: '149274182505-6mef0v0bvk203pc173v83k03pmc2aiha.apps.googleusercontent.com',
    iosBundleId: 'com.example.loyalappco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgXiKztzfEQarlh9XpjsjgueND1pcUqew',
    appId: '1:149274182505:ios:1296adf4eeecb66a14f3f8',
    messagingSenderId: '149274182505',
    projectId: 'loyalapp-2beb0',
    storageBucket: 'loyalapp-2beb0.appspot.com',
    iosClientId: '149274182505-6mef0v0bvk203pc173v83k03pmc2aiha.apps.googleusercontent.com',
    iosBundleId: 'com.example.loyalappco',
  );
}
